### ISSUE TITLE
Non-runnable checklists

### ISSUE THREAD

**Issue by sundhaug92** [ReentryGame/DefaultChecklists#3]
# Mercury
- [ ] [Mercury/AscentSECO/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/Mercury/AscentSECO/checklist.json)
- [ ] [Mercury/EmerLanding/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/Mercury/EmerLanding/checklist.json)
- [ ] [Mercury/EmerOrbit/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/Mercury/EmerOrbit/checklist.json)
- [ ] [Mercury/EmerRetrograde/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/Mercury/EmerRetrograde/checklist.json)
- [ ] [Mercury/EmergencyAscent/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/Mercury/EmergencyAscent/checklist.json)
- [ ] [Mercury/EntryRetro/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/Mercury/EntryRetro/checklist.json)
- [ ] [Mercury/SystemGyroAlign/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/Mercury/SystemGyroAlign/checklist.json)
- [ ] [Mercury/SystemsPreDark/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/Mercury/SystemsPreDark/checklist.json)

# Gemini
- [ ] [Gemini/AgenaAgenaCommands/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/Gemini/AgenaAgenaCommands/checklist.json)
- [ ] [Gemini/EVAPostEVA/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/Gemini/EVAPostEVA/checklist.json)
- [ ] [Gemini/EVAPreEVA/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/Gemini/EVAPreEVA/checklist.json)
- [ ] [Gemini/OrbitingCircOrbit/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/Gemini/OrbitingCircOrbit/checklist.json)
- [ ] [Gemini/OrbitingPlatformAlign/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/Gemini/OrbitingPlatformAlign/checklist.json)
- [ ] [Gemini/RnDDocking/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/Gemini/RnDDocking/checklist.json)
- [ ] [Gemini/RnDPostDocking/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/Gemini/RnDPostDocking/checklist.json)
- [ ] [Gemini/RnDRendezvous/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/Gemini/RnDRendezvous/checklist.json)
- [ ] [Gemini/RnDUndocking/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/Gemini/RnDUndocking/checklist.json)

# Apollo
## Command Module
- [ ] [CommandModule/AGCP79FinalRendezvous/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/CommandModule/AGCP79FinalRendezvous/checklist.json)
- [ ] [CommandModule/EntryEarthLanding/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/CommandModule/EntryEarthLanding/checklist.json)
- [ ] [CommandModule/EntryEarthOrbitEntryVehicle/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/CommandModule/EntryEarthOrbitEntryVehicle/checklist.json)
- [ ] [CommandModule/EntryPostLanding/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/CommandModule/EntryPostLanding/checklist.json)
- [ ] [CommandModule/EntrySPSDeorbitAndEntry/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/CommandModule/EntrySPSDeorbitAndEntry/checklist.json)
- [ ] [CommandModule/InsertionECS/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/CommandModule/InsertionECS/checklist.json)
- [ ] [CommandModule/InsertionPyros/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/CommandModule/InsertionPyros/checklist.json)
- [ ] [CommandModule/LMInterfaceEVACSMActiveDocking/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/CommandModule/LMInterfaceEVACSMActiveDocking/checklist.json)
- [ ] [CommandModule/LMInterfaceEVALMActiveDocking/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/CommandModule/LMInterfaceEVALMActiveDocking/checklist.json)
- [ ] [CommandModule/PreLaunchPreFlight/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/CommandModule/PreLaunchPreFlight/checklist.json)
- [ ] [CommandModule/SystemCabinSuitPSICheck/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/CommandModule/SystemCabinSuitPSICheck/checklist.json)
- [ ] [CommandModule/SystemCnWsOps/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/CommandModule/SystemCnWsOps/checklist.json)
- [ ] [CommandModule/SystemDockingProbe/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/CommandModule/SystemDockingProbe/checklist.json)
- [ ] [CommandModule/SystemECSMon/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/CommandModule/SystemECSMon/checklist.json)
- [ ] [CommandModule/SystemEPSMon/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/CommandModule/SystemEPSMon/checklist.json)
- [ ] [CommandModule/SystemFuelCellPurgeCheck/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/CommandModule/SystemFuelCellPurgeCheck/checklist.json)
- [ ] [CommandModule/SystemSMRCSMon/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/CommandModule/SystemSMRCSMon/checklist.json)
- [ ] [CommandModule/SystemSPSMon/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/CommandModule/SystemSPSMon/checklist.json)
- [ ] [CommandModule/SystemWaterGlycolCheck/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/CommandModule/SystemWaterGlycolCheck/checklist.json)
- [ ] [CommandModule/TnDCSMTransposition/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/CommandModule/TnDCSMTransposition/checklist.json)
- [ ] [CommandModule/TnDDocking/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/CommandModule/TnDDocking/checklist.json)
- [ ] [CommandModule/TnDPostDocking/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/CommandModule/TnDPostDocking/checklist.json)

## Lunar Module
- [ ] [LunarModule/ActivationAPSDPSPrepressurization/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/LunarModule/ActivationAPSDPSPrepressurization/checklist.json)
- [ ] [LunarModule/ActivationCnW/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/LunarModule/ActivationCnW/checklist.json)
- [ ] [LunarModule/ActivationCommunication/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/LunarModule/ActivationCommunication/checklist.json)
- [ ] [LunarModule/ActivationECS/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/LunarModule/ActivationECS/checklist.json)
- [ ] [LunarModule/ActivationEPS/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/LunarModule/ActivationEPS/checklist.json)
- [ ] [LunarModule/ActivationTimers/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/LunarModule/ActivationTimers/checklist.json)
- [ ] [LunarModule/EPS_BasicStaged/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/LunarModule/EPS_BasicStaged/checklist.json)
- [ ] [LunarModule/EPS_BasicUnstaged/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/LunarModule/EPS_BasicUnstaged/checklist.json)
- [ ] [LunarModule/EPS_LunarStayBtryMgnt/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/LunarModule/EPS_LunarStayBtryMgnt/checklist.json)
- [ ] [LunarModule/EPS_PeriodicMonStaged/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/LunarModule/EPS_PeriodicMonStaged/checklist.json)
- [ ] [LunarModule/EPS_PeriodicMonUnstaged/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/LunarModule/EPS_PeriodicMonUnstaged/checklist.json)
- [ ] [LunarModule/EPS_PostDPSBurn/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/LunarModule/EPS_PostDPSBurn/checklist.json)
- [ ] [LunarModule/EPS_PrepDPSBurn/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/LunarModule/EPS_PrepDPSBurn/checklist.json)
- [ ] [LunarModule/IntravehicularTransfer/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/LunarModule/IntravehicularTransfer/checklist.json)
- [ ] [LunarModule/LRV_Checks/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/LunarModule/LRV_Checks/checklist.json)
- [ ] [LunarModule/LRV_ConfigScienceStop/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/LunarModule/LRV_ConfigScienceStop/checklist.json)
- [ ] [LunarModule/LRV_PayloadLoading/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/LunarModule/LRV_PayloadLoading/checklist.json)
- [ ] [LunarModule/LRV_PostDeployment/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/LunarModule/LRV_PostDeployment/checklist.json)
- [ ] [LunarModule/LRV_PostSortie/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/LunarModule/LRV_PostSortie/checklist.json)
- [ ] [LunarModule/LRV_PreSortie/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/LunarModule/LRV_PreSortie/checklist.json)
- [ ] [LunarModule/LunarAscentLMDocking/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/LunarModule/LunarAscentLMDocking/checklist.json)
- [ ] [LunarModule/LunarAscentP12/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/LunarModule/LunarAscentP12/checklist.json)
- [ ] [LunarModule/LunarAscentP20/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/LunarModule/LunarAscentP20/checklist.json)
- [ ] [LunarModule/LunarAscentRendezvousSimplified/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/LunarModule/LunarAscentRendezvousSimplified/checklist.json)
- [ ] [LunarModule/MPSDPSEngOnOff/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/LunarModule/MPSDPSEngOnOff/checklist.json)
- [ ] [LunarModule/MPSP41RCSBurn/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/LunarModule/MPSP41RCSBurn/checklist.json)
- [ ] [LunarModule/MPSProgram30/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/LunarModule/MPSProgram30/checklist.json)
- [ ] [LunarModule/MPS_APSRCSPrplntIntrcn/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/LunarModule/MPS_APSRCSPrplntIntrcn/checklist.json)
- [ ] [LunarModule/MPS_BasicStaged/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/LunarModule/MPS_BasicStaged/checklist.json)
- [ ] [LunarModule/MPS_BasicUnstaged/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/LunarModule/MPS_BasicUnstaged/checklist.json)
- [ ] [LunarModule/MPS_PeriodicMonAPS/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/LunarModule/MPS_PeriodicMonAPS/checklist.json)
- [ ] [LunarModule/MPS_PeriodicMonDPS/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/LunarModule/MPS_PeriodicMonDPS/checklist.json)
- [ ] [LunarModule/MPS_PeriodicMonRCS/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/LunarModule/MPS_PeriodicMonRCS/checklist.json)
- [ ] [LunarModule/PGNS_DAPSetup/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/LunarModule/PGNS_DAPSetup/checklist.json)
- [ ] [LunarModule/PGNS_IMUPowerUp/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/LunarModule/PGNS_IMUPowerUp/checklist.json)
- [ ] [LunarModule/PGNS_LGCFreshStart/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/LunarModule/PGNS_LGCFreshStart/checklist.json)
- [ ] [LunarModule/PGNS_LGCPowerUp/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/LunarModule/PGNS_LGCPowerUp/checklist.json)
- [ ] [LunarModule/PoweredDescentP63BreakingPhase/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/LunarModule/PoweredDescentP63BreakingPhase/checklist.json)
- [ ] [LunarModule/PoweredDescentP64/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/LunarModule/PoweredDescentP64/checklist.json)
- [ ] [LunarModule/PoweredDescentP66/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/LunarModule/PoweredDescentP66/checklist.json)
- [ ] [LunarModule/PoweredDescentP68/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/LunarModule/PoweredDescentP68/checklist.json)
- [ ] [LunarModule/PoweredDescentUndockFromCSM/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/LunarModule/PoweredDescentUndockFromCSM/checklist.json)
- [ ] [LunarModule/PreLaunchCloseout/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/LunarModule/PreLaunchCloseout/checklist.json)
- [ ] [LunarModule/Radar_LdgRdrCheckout/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/LunarModule/Radar_LdgRdrCheckout/checklist.json)
- [ ] [LunarModule/Radar_LdgRdrPowerUp/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/LunarModule/Radar_LdgRdrPowerUp/checklist.json)
- [ ] [LunarModule/Radar_RndzRdrCheckout/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/LunarModule/Radar_RndzRdrCheckout/checklist.json)
- [ ] [LunarModule/Radar_RndzRdrPowerUp/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/LunarModule/Radar_RndzRdrPowerUp/checklist.json)
- [ ] [LunarModule/StagingAPSPressurization/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/LunarModule/StagingAPSPressurization/checklist.json)
- [ ] [LunarModule/StagingDPSPropTankVent/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/LunarModule/StagingDPSPropTankVent/checklist.json)
- [ ] [LunarModule/StagingDPSSupCritHeVent/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/LunarModule/StagingDPSSupCritHeVent/checklist.json)
- [ ] [LunarModule/StagingEDPrestage/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/LunarModule/StagingEDPrestage/checklist.json)
- [ ] [LunarModule/StagingEPSPrestage/checklist.json](https://github.com/ReentryGame/DefaultChecklists/blob/master/LunarModule/StagingEPSPrestage/checklist.json)

**Comment by papymaj5** [comment]
@sundhaug92 we probably should update this list or just remove it completely
