### ISSUE TITLE
Regarding the Boost checklist 

### ISSUE THREAD

**Issue by 343GuiltySpark-04** [ReentryGame/DefaultChecklists#31]
it seems that V66 and then V45 does not program the DAP, that said we should probably direct the player to the V48 checklist and add a entry in the checklist stating the default values. at least until its fixed/implemented (idk if its a game bug or V66 is not implemented yet).

**Comment by sundhaug92** [comment]
CM or LM?

**Comment by 343GuiltySpark-04** [comment]
CM
