### ISSUE TITLE
Gemini: Agena Docking CL De-Rigidize

### ISSUE THREAD

**Issue by Valkyrien04** [ReentryGame/DefaultChecklists#49]
![image](https://user-images.githubusercontent.com/1189321/152625378-d646800b-a38f-4160-84e0-f657e3f07da5.png)

**Comment by sundhaug92** [comment]
Relevant line seems to be https://github.com/ReentryGame/DefaultChecklists/blob/009dc2ae07312a7080001f9c0306972993a0361d/Gemini/RnDDocking/checklist.json#L8, @papymaj5

**Comment by sundhaug92** [comment]
I think this is fixed now
